# Generated by Django 3.0 on 2020-03-15 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField(default='请再次输入留言内容', verbose_name='留言')),
                ('dates', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('praise_counts', models.IntegerField(default=0, help_text='这里会自动登记，请不要改', verbose_name='点赞量')),
                ('tread_counts', models.IntegerField(default=0, help_text='这里会自动登记，请不要改', verbose_name='差评量')),
                ('times', models.CharField(default=0, help_text='这里会自动登记，请不要改', max_length=30, verbose_name='留言者留言次数')),
                ('msg_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_author', to=settings.AUTH_USER_MODEL, verbose_name='留言者')),
            ],
            options={
                'ordering': ('-praise_counts',),
            },
            managers=[
                ('message_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Message_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.CharField(default=0, help_text='这里会自动登记，请不要改', max_length=30, verbose_name='评论次数')),
                ('tread_counts', models.IntegerField(default=0, help_text='这里会自动登记，请不要改', verbose_name='差评量')),
                ('praise_counts', models.IntegerField(default=0, help_text='这里会自动登记，请不要改', verbose_name='点赞量')),
                ('dates', models.DateTimeField(auto_now_add=True)),
                ('reply_content', models.TextField(default='请输入回复内容', verbose_name='回复内容')),
                ('message', models.ForeignKey(help_text='请选择针对哪条留言', on_delete=django.db.models.deletion.CASCADE, related_name='message', to='comment.Message', verbose_name='留言')),
                ('reply_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_author', to=settings.AUTH_USER_MODEL, verbose_name='回复者')),
            ],
            options={
                'ordering': ('-dates',),
            },
            managers=[
                ('message_reply_', django.db.models.manager.Manager()),
            ],
        ),
    ]
