# Generated by Django 3.0 on 2020-03-15 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_reply',
            name='message',
            field=models.ForeignKey(help_text='请选择针对哪条留言', on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='comment.Message', verbose_name='留言'),
        ),
    ]
