# Generated by Django 3.0 on 2020-03-16 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0002_auto_20200315_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_author',
            field=models.ForeignKey(help_text='请选择自己的账号', on_delete=django.db.models.deletion.CASCADE, related_name='msg_author', to=settings.AUTH_USER_MODEL, verbose_name='留言者'),
        ),
        migrations.AlterField(
            model_name='message_reply',
            name='reply_author',
            field=models.ForeignKey(help_text='请选择自己的账号', on_delete=django.db.models.deletion.CASCADE, related_name='reply_author', to=settings.AUTH_USER_MODEL, verbose_name='回复者'),
        ),
    ]
