# Generated by Django 3.0 on 2020-03-15 14:37

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lagou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
                ('education', models.CharField(max_length=50, verbose_name='学历')),
                ('industry', models.CharField(max_length=50, verbose_name='企业')),
                ('job', models.CharField(max_length=50, verbose_name='职位')),
                ('recruit_name', models.CharField(max_length=50, verbose_name='发布招聘时间')),
                ('salary', models.CharField(max_length=20, verbose_name='月薪')),
                ('scale', models.CharField(default='', max_length=50, verbose_name='企业规模')),
                ('technique_key', models.CharField(default='', max_length=50, verbose_name='技术关键词')),
                ('treatment', models.CharField(default='', max_length=100, verbose_name='待遇')),
            ],
            managers=[
                ('lagou_', django.db.models.manager.Manager()),
            ],
        ),
    ]
