# Generated by Django 3.0 on 2020-03-15 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainsite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='确保标题和文章内容对应', max_length=50, verbose_name='笔记标题')),
                ('type', models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Java', 'Java'), ('Scrapy', 'Scrapy'), ('Pandas', 'Pandas'), ('Numpy', 'Numpy'), ('Layui', 'Layui'), ('English', 'English'), ('machine_learning', 'machine_learning'), ('C#', 'C#'), ('C++', 'C++'), ('Linux', 'Linux'), ('Mysql', 'Mysql'), ('Leetcode', 'Leetcode'), ('Cmd', 'Cmd'), ('jquery', 'jquery'), ('个人信息', '个人信息'), ('Celery', 'Celery'), ('Pyecharts', 'Pyecharts'), ('javaScripts', 'javaScripts'), ('Restful Api', 'Restful Api'), ('Flask', 'Flask'), ('深度学习', '深度学习'), ('Redis', 'Redis'), ('Mongodb', 'Mongodb'), ('Spring', 'Spring'), ('Oracle', 'Oracle')], help_text='选择记录的笔记类型', max_length=20, verbose_name='笔记类型')),
                ('publish_date', models.DateField(auto_now_add=True, max_length=30, verbose_name='发布日期')),
                ('key_word', models.CharField(help_text='提取文章主要的关键字', max_length=100, null=True, verbose_name='关键字')),
                ('slug', models.SlugField(help_text='根据它可以通过url找到你的笔记', verbose_name='笔记url')),
                ('note_contents', mdeditor.fields.MDTextField(verbose_name='内容')),
                ('praise', models.IntegerField(default=0, help_text='会自动记录，请不要修改', verbose_name='点赞量')),
                ('read_counts', models.IntegerField(default=0, help_text='会自动记录，请不要修改', verbose_name='阅读量')),
                ('shorthand', models.TextField(help_text='大致描述一下你的笔记内容', verbose_name='简介')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn'), ('u', 'Unstart')], default='u', help_text='您的笔记当前所属状态', max_length=1, verbose_name='文章状态')),
                ('note_author', models.ForeignKey(help_text='选择自己', on_delete=django.db.models.deletion.CASCADE, related_name='note_author', to=settings.AUTH_USER_MODEL, verbose_name='笔者')),
            ],
            options={
                'ordering': ('-publish_date',),
                'permissions': (('publish_article', '发布文章'), ('draft_article', '起草文章')),
            },
            managers=[
                ('note_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Note_criticism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('praise_counts', models.IntegerField(default=0, help_text='会自动记录，请不要修改', verbose_name='点赞量')),
                ('tread_counts', models.IntegerField(default=0, help_text='会自动记录，请不要修改', verbose_name='差评量')),
                ('times', models.IntegerField(default=0, help_text='会自动记录，请不要修改', verbose_name='该用户评论总次数')),
                ('dates', models.DateTimeField(auto_now_add=True, verbose_name='评论日期')),
                ('criticism_content', models.TextField(default='请填写评论内容', verbose_name='评论内容')),
                ('criticism_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criticism_author', to='mainsite.Information', verbose_name='笔记评论者')),
                ('note_slug', models.ForeignKey(help_text='请不要修改', on_delete=django.db.models.deletion.CASCADE, related_name='note_slug', to='notes.Note', verbose_name='笔记')),
            ],
            options={
                'ordering': ('-dates',),
            },
            managers=[
                ('Note_criticism_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Note_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('praise_counts', models.IntegerField(default=0, help_text='会自动记录，请不要修改', verbose_name='点赞量')),
                ('tread_counts', models.IntegerField(default=0, help_text='会自动记录，请不要修改', verbose_name='差评量')),
                ('times', models.IntegerField(default=0, help_text='会自动记录，请不要修改', verbose_name='该用户回复当前笔记总次数')),
                ('dates', models.DateTimeField(auto_now_add=True, verbose_name='评论日期')),
                ('reply_content', models.TextField(default='请填写回复内容', verbose_name='回复内容')),
                ('note_criticism', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='note_reply', to='notes.Note_criticism', verbose_name='笔记评论')),
                ('reply_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criticism_reply_author', to='mainsite.Information', verbose_name='回复者')),
            ],
            options={
                'ordering': ('-dates',),
            },
            managers=[
                ('Note_reply_', django.db.models.manager.Manager()),
            ],
        ),
    ]
