# Generated by Django 3.0 on 2020-03-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='publish_date',
            field=models.DateField(auto_now=True, max_length=30, verbose_name='发布日期'),
        ),
    ]
