# Generated by Django 3.0 on 2020-03-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_modify_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(help_text='根据它可以通过url找到你的笔记,强烈建议格式为  "你的用户名_title"', verbose_name='笔记url'),
        ),
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', help_text='您的笔记当前所属状态', max_length=15, verbose_name='文章状态'),
        ),
    ]
