# Generated by Django 3.0 on 2020-03-15 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ips', models.CharField(max_length=30, verbose_name='ip地址')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='登录时间')),
                ('ips_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_author', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'ordering': ('-time',),
            },
            managers=[
                ('ip_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motto', models.CharField(default='', help_text='格言不超过200个字', max_length=200, verbose_name='格言')),
                ('hobby', models.CharField(default='', help_text='爱好不超过200个字', max_length=200, verbose_name='爱好')),
                ('head_image', models.ImageField(help_text='支持所有正常头像格式', upload_to='head', verbose_name='头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='已认证用户')),
            ],
            options={
                'verbose_name': '用户详情',
                'verbose_name_plural': '用户详情',
            },
            managers=[
                ('information_', django.db.models.manager.Manager()),
            ],
        ),
    ]
