# Generated by Django 2.2.11 on 2020-06-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inform_time', models.DateField(auto_now_add=True, verbose_name='通知发布日期')),
                ('inform_content', models.TextField(verbose_name='通知内容')),
                ('inform_title', models.CharField(help_text='不多于50个字', max_length=50, verbose_name='通知标题')),
                ('inform_type', models.CharField(choices=[('1', '网站最新修改通知'), ('2', '广告通知'), ('3', '网站维护通知')], max_length=1, verbose_name='通知类型')),
                ('is_publish', models.BooleanField(default=False, verbose_name='是否发布网站')),
            ],
            options={
                'verbose_name': '网站通知',
                'verbose_name_plural': '网站通知',
                'ordering': ('-inform_time',),
            },
        ),
    ]
