# Generated by Django 2.2.11 on 2020-06-17 11:43

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='inform',
            managers=[
                ('inform_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='inform',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='是否已发布'),
        ),
    ]
