# Generated by Django 3.0 on 2020-03-15 14:37

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_keyword', models.CharField(max_length=30, verbose_name='职位关键词')),
                ('city', models.CharField(max_length=40, verbose_name='地区')),
                ('salary', models.CharField(max_length=30, verbose_name='月薪')),
                ('industry', models.CharField(max_length=50, verbose_name='公司名称')),
                ('technology_keyword', models.CharField(max_length=50, verbose_name='技术关键词')),
                ('scale', models.CharField(max_length=100, verbose_name='公司规模')),
                ('treatment', models.CharField(max_length=50, verbose_name='待遇')),
                ('education', models.CharField(max_length=50, verbose_name='需求门槛')),
                ('publish_time', models.CharField(max_length=30, verbose_name='职位发布日期')),
            ],
            managers=[
                ('job_', django.db.models.manager.Manager()),
            ],
        ),
    ]
